language: node_js
before_script:
  - yarn global add gatsby-cli
cache:
  yarn: true
node_js:
  - "12"
  - "10"
deploy:
  provider: script
  script: yarn install && yarn run deploy
  skip_cleanup: true
  on:
    branch: master
