language: node_js
before_script:
  - yarn global add gatsby-cli
cache:
  yarn: true
node_js:
  - "12"
deploy:
  provider: script
  github-token: $GITHUB_TOKEN
  script: yarn install && yarn run deploy
  skip_cleanup: true
  local_dir: public
  keep-history: true
  on:
    branch: master
